# Generated by Django 4.0 on 2021-12-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('name', models.CharField(max_length=120, verbose_name='Название проекта')),
            ],
            options={
                'verbose_name': 'Проект из портфолио',
                'verbose_name_plural': 'Проекты из портфолио',
            },
        ),
    ]
