# Generated by Django 4.0 on 2022-02-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioproject_name_en_portfolioproject_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioproject',
            old_name='name_ua',
            new_name='name_uk',
        ),
    ]
