# Generated by Django 4.0 on 2022-01-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('button_1_link', models.URLField(blank=True, null=True)),
                ('button_1_text', models.TextField(blank=True, null=True)),
                ('button_2_link', models.URLField(blank=True, null=True)),
                ('button_2_text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='header-images/')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
