# Generated by Django 4.0 on 2022-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_headerslide_button_1_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Основной контент')),
            ],
            options={
                'verbose_name': 'Текст в услугах',
                'verbose_name_plural': 'Тексты в услугах',
            },
        ),
    ]
