# Generated by Django 4.0 on 2022-01-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images/', verbose_name='Картинка')),
                ('name', models.CharField(max_length=120, verbose_name='Название проекта')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Наша команда',
            },
        ),
    ]
